### ISSUE TITLE
Where is logger command output?

### ISSUE THREAD

**Issue by Shoothzj** [rsyslog/rsyslog-docker#35]
I clone this repo, and try it myself. I found what I interaction with bash was directed into system output(I can see by "docker logs" command). I try command "logger hello", can't find it anywhere ? And how to close the behaviour that loging my interaction with bash

**Comment by rgerhards** [comment]
I think logger will always write to the system log socket and thus need rsyslog to run in the background. This is not case. Note that this repo takes care of use cases where rsyslog shall operate as a log server.
